module.exports = {
  post: "Item could not be found",
  postBad: "Could not add stops",
  getRandomBad: "Could not get random stop from the database.",
  getRandomUserBad: "Could not get random user from the database.",
  getShowAllStopsBad: "Could not get stops from the database.",
  getShowAllTripsBad: "Could not get trips from the database.",
  getByIdBad: "Could not get stop from the database.",
  getByUserIdBad: "Could not get user from the database.",
  getByTripIdBad: "Could not get trip from the database.",
  getAllBad: "There was a problem finding stops.",
  getAllTripsBad: "There was a problem finding trips.",
  getAllUsersBad: "There was a problem finding users.",
  deleteByBad: "Stops could not be deleted.",
  deleteByTripBad: "Trips could not be deleted.",
  deleteByIdBad: "Could not delete stop from the database.",
  deleteByIdGood: "Stop has been removed from the database.",
  deleteByTripIdGood: "Trip has been removed from the database.",
  putByIdBad: "Could not update stop.",
  putByUserIdBad: "Could not update user.",
  putByTripIdBad: "Could not update trip.",
  deleteRemoveAll: "Stops successfully deleted",
  deleteRemoveAllBad: "Oops something went wrong",
};
